# Generated by Django 3.2.18 on 2023-05-13 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_userprofile_favourites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="favourites",
        ),
    ]
