# Generated by Django 3.2.18 on 2023-05-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20230515_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount in Percentage', max_digits=6),
        ),
    ]
