# Generated by Django 3.2.18 on 2023-06-07 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_value',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Coupon Quantity'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
