# Generated by Django 3.2.18 on 2023-05-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_products_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(default=False),
        ),
    ]
