# Generated by Django 3.2.18 on 2023-05-06 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230504_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
