# Generated by Django 3.2.18 on 2023-05-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourites',
        ),
    ]
