# Generated by Django 3.2.18 on 2023-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_remove_userprofile_favourites"),
        ("products", "0007_remove_product_favourites"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="favourites",
            field=models.ManyToManyField(to="profiles.UserProfile"),
        ),
    ]
