# Generated by Django 3.2.18 on 2023-05-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_product_favourites"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
