# Generated by Django 3.2.18 on 2023-05-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourites',
        ),
    ]
