# Generated by Django 3.2.18 on 2023-05-25 12:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0010_remove_product_favourites"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reviews",
            unique_together={("user", "product")},
        ),
    ]
