# Generated by Django 3.2.18 on 2023-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='reviews per user'),
        ),
    ]
