# Generated by Django 3.2.18 on 2023-05-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_auto_20230525_1212"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reviews",
            name="reviews per user",
        ),
        migrations.AddConstraint(
            model_name="reviews",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="reviews_per_user"
            ),
        ),
    ]
