# Generated by Django 3.2.18 on 2023-06-03 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_alter_product_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
    ]
