# Generated by Django 3.2.18 on 2023-06-21 12:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0025_alter_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                default=products.models.generate_sku,
                help_text="SKU randomly generated",
                max_length=6,
                unique=True,
            ),
        ),
    ]
